"""Provider-neutral contracts for private personal portfolio integration.

This package intentionally contains no concrete provider network client and no MCP dependency.
The bounded-auth module defines only a server/local transport protocol and one-shot safety gates.
"""

from .bounded_auth import (
    ACTIVATION_PATH,
    BOUNDED_AUTH_POLICY_V1,
    KSEI_PORTFOLIO_ENDPOINTS,
    KSEI_SERVICE_BASE,
    LOGIN_PATH,
    ActivationResult,
    BoundedAuthPolicy,
    BoundedAuthReport,
    BoundedAuthRunner,
    BoundedKseiTransport,
    BoundedTransportFailure,
    EndpointTarget,
    EphemeralCredentials,
    EphemeralSecret,
    LoginResult,
    ProbeFailureCode,
    ProviderResponse,
    SanitizedResponseObservation,
    SummaryProbe,
    describe_json_shape,
    probe_summary_semantics,
    prompt_ephemeral_credentials,
)
from .schema import PERSONAL_PORTFOLIO_SNAPSHOT_SCHEMA_V1, validate_snapshot_payload
from .store import SqlitePortfolioSnapshotStore
from .surface import (
    AppendResult,
    AssetClass,
    CashBalance,
    CorporateActionContext,
    EndpointClass,
    EndpointEvidence,
    EndpointFailureCode,
    FinancialPITContext,
    HoldingEnrichment,
    InvestmentHealthContext,
    PersonalPortfolioAdapter,
    PortfolioPosition,
    PortfolioProvenance,
    PortfolioSnapshot,
    PortfolioSnapshotStore,
    PricePerformanceContext,
    REQUIRED_ENDPOINT_CLASSES,
    REQUIRED_SOURCE_COMMIT_PINS,
    SecurityIdentity,
    ShortHorizonModelContext,
    SnapshotCompleteness,
    TradingOpportunityContext,
    assert_minimized_canonical_payload,
    derive_subaccount_ref,
    new_scope_ref,
)

__all__ = [
    "ACTIVATION_PATH",
    "AppendResult",
    "AssetClass",
    "ActivationResult",
    "BOUNDED_AUTH_POLICY_V1",
    "BoundedAuthPolicy",
    "BoundedAuthReport",
    "BoundedAuthRunner",
    "BoundedKseiTransport",
    "BoundedTransportFailure",
    "CashBalance",
    "CorporateActionContext",
    "EndpointClass",
    "EndpointEvidence",
    "EndpointFailureCode",
    "EndpointTarget",
    "EphemeralCredentials",
    "EphemeralSecret",
    "FinancialPITContext",
    "HoldingEnrichment",
    "InvestmentHealthContext",
    "KSEI_PORTFOLIO_ENDPOINTS",
    "KSEI_SERVICE_BASE",
    "LOGIN_PATH",
    "LoginResult",
    "PERSONAL_PORTFOLIO_SNAPSHOT_SCHEMA_V1",
    "PersonalPortfolioAdapter",
    "PortfolioPosition",
    "PortfolioProvenance",
    "PortfolioSnapshot",
    "PortfolioSnapshotStore",
    "PricePerformanceContext",
    "ProbeFailureCode",
    "ProviderResponse",
    "REQUIRED_ENDPOINT_CLASSES",
    "REQUIRED_SOURCE_COMMIT_PINS",
    "SanitizedResponseObservation",
    "SecurityIdentity",
    "ShortHorizonModelContext",
    "SnapshotCompleteness",
    "SqlitePortfolioSnapshotStore",
    "SummaryProbe",
    "TradingOpportunityContext",
    "assert_minimized_canonical_payload",
    "derive_subaccount_ref",
    "describe_json_shape",
    "new_scope_ref",
    "probe_summary_semantics",
    "prompt_ephemeral_credentials",
    "validate_snapshot_payload",
]
